<!DOCTYPE html PUBLIC= "-//W3C/DTD XHML 1.0 Transitional//EN"
    "http://www.w3c.org/TR/xhtml1-transitional.dtd">
<html xml:lang="en" xmlns="http://www-w3c.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
</head>
<body>
    <h1><?php echo $this->escape($this->title) ?></h1>
    <?php echo $this->layout()->content; ?>
</body>
</html>